language: java
jdk:
    - openjdk7
    - oraclejdk8
before_install:
    - cp ./etc/settings.xml ~/.m2/
    - cp ./etc/settings-arquillian.xml ~/
    - cp ./etc/onFailure.sh  ~/
    - cp ./etc/onSuccess.sh  ~/
    - cp ./etc/logging.properties  ~/
    - chmod 777 ~/onFailure.sh
    - chmod 777 ~/onSuccess.sh
script:
    - mvn -B clean verify cobertura:cobertura coveralls:cobertura -Dorg.apache.maven.user-settings=~/settings-arquillian.xml -Dorg.apache.maven.global-settings=~/settings-arquillian.xml
after_failure: ~/onFailure.sh
after_success: ~/onSuccess.sh
notifications:
    email: false
    irc:
        channels:
            - chat.freenode.net#lightblue
    on_success: always
env:
    global:
        - secure: f7LSDiKEDZ/d+2mg5Qf8Qe7S9umADCH98NVnuOHd+fUOAq0S1L8olBZf0PTck2zQejh9g/b/vHFURFTQ2ukRAiK9t7Kb+8OMkXikOpY3HzOD3+r8kMQMYWwXutA2kXw1mRjctO0qLQOxvpDeaBDuD1IWtx9Mm5W9fAhfrjlNP6g=
        - secure: NIRUn/mE0mHxoHRwrGl5MXEZWroOs4ZKoIFIYk+aUJuKuR4EbEnIJRH/YFtq5m/fZGD6ZOVCybEQIxqzVum6o0EqlhIsaLSmhWD/RGgUyHTpQBn2subGb1+BZHSk93kU4giEx+vP0pUpTvJ+gn/yJM0lWoaaA37HPqzeLsuNixI=
